site_name: chemcloud
site_url: https://mtzgroup.github.io/chemcloud-client/
theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: amber
  features:
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.expand
  icon:
    repo: fontawesome/brands/github-alt

repo_url: https://github.com/mtzgroup/chemcloud-client
edit_uri: edit/develop/docs/
site_author: Colton Hicks
extra_css:
  - css/extra.css
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_root_heading: False
            show_root_full_path: True
            show_category_heading: True
            show_signature_annotations: True
            show_if_no_docstring: True
            group_by_category: True
            heading_level: 2
          selection:
            new_path_syntax: True
            inherited_members: True
            filters:
              - "!^_"
              - "^__init__$"
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - toc:
      permalink: 🔗
  - markdown_include.include:
      base_path: docs

nav:
  - chemcloud: index.md
  - Tutorial - Users Guide:
      - tutorial/compute.md
      - tutorial/supported-programs.md
      - tutorial/authentication.md
      - tutorial/geometry-optimization.md
      - tutorial/batch-computations.md
      - tutorial/bigchem-algorithms.md
  - Code Reference:
      - code-reference/CCClient.md
      - code-reference/FutureOutputs.md
      - code-reference/ProgramInputs.md
      - code-reference/ProgramOutputs.md
      - code-reference/exceptions.md
  - Changelog: CHANGELOG.md
